name: 'Thank You Action'
description: 'Say "Thank You" to new pull requests'
author: 'Kulifay Zsolt'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: false
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
